import QtQuick 2.15
import org.kde.kcmutils as KCM

KCM.SimpleKCM {

    property var cfg_showOnlyCurrentScreen
    property var cfg_showOnlyCurrentScreenDefault
    property var cfg_showOnlyCurrentDesktop
    property var cfg_showOnlyCurrentDesktopDefault
    property var cfg_showOnlyCurrentActivity
    property var cfg_showOnlyCurrentActivityDefault
    property var cfg_showOnlyMinimized
    property var cfg_showOnlyMinimizedDefault
    property var cfg_unhideOnAttention
    property var cfg_unhideOnAttentionDefault
    property var cfg_groupingStrategy
    property var cfg_groupingStrategyDefault
    property var cfg_iconOnly
    property var cfg_iconOnlyDefault
    property var cfg_groupedTaskVisualization
    property var cfg_groupedTaskVisualizationDefault
    property var cfg_groupPopups
    property var cfg_groupPopupsDefault
    property var cfg_onlyGroupWhenFull
    property var cfg_onlyGroupWhenFullDefault
    property var cfg_groupingAppIdBlacklist
    property var cfg_groupingAppIdBlacklistDefault
    property var cfg_groupingLauncherUrlBlacklist
    property var cfg_groupingLauncherUrlBlacklistDefault
    property var cfg_sortingStrategy
    property var cfg_sortingStrategyDefault
    property var cfg_separateLaunchers
    property var cfg_separateLaunchersDefault
    property var cfg_maxStripes
    property var cfg_maxStripesDefault
    property var cfg_maxButtonLength
    property var cfg_maxButtonLengthDefault
    property var cfg_forceStripes
    property var cfg_forceStripesDefault
    property var cfg_showToolTips
    property var cfg_showToolTipsDefault
    property var cfg_wheelEnabled
    property var cfg_wheelEnabledDefault
    property var cfg_wheelSkipMinimized
    property var cfg_wheelSkipMinimizedDefault
    property var cfg_highlightWindows
    property var cfg_highlightWindowsDefault
    property var cfg_launchers
    property var cfg_launchersDefault
    property var cfg_middleClickAction
    property var cfg_middleClickActionDefault
    property var cfg_indicateAudioStreams
    property var cfg_indicateAudioStreamsDefault
    property var cfg_iconScale
    property var cfg_iconScaleDefault
    property var cfg_iconSizePx
    property var cfg_iconSizePxDefault
    property var cfg_iconSizeOverride
    property var cfg_iconSizeOverrideDefault
    property var cfg_taskHoverEffect
    property var cfg_taskHoverEffectDefault
    property var cfg_maxTextLines
    property var cfg_maxTextLinesDefault
    property var cfg_minimizeActiveTaskOnClick
    property var cfg_minimizeActiveTaskOnClickDefault
    property var cfg_reverseMode
    property var cfg_reverseModeDefault
    property var cfg_iconSpacing
    property var cfg_iconSpacingDefault
    property var cfg_indicatorsEnabled
    property var cfg_indicatorsEnabledDefault
    property var cfg_indicatorProgress
    property var cfg_indicatorProgressDefault
    property var cfg_indicatorProgressColor
    property var cfg_indicatorProgressColorDefault
    property var cfg_disableInactiveIndicators
    property var cfg_disableInactiveIndicatorsDefault
    property var cfg_indicatorsAnimated
    property var cfg_indicatorsAnimatedDefault
    property var cfg_groupIconEnabled
    property var cfg_groupIconEnabledDefault
    property var cfg_indicatorLocation
    property var cfg_indicatorLocationDefault
    property var cfg_indicatorStyle
    property var cfg_indicatorStyleDefault
    property var cfg_indicatorMinLimit
    property var cfg_indicatorMinLimitDefault
    property var cfg_indicatorMaxLimit
    property var cfg_indicatorMaxLimitDefault
    property var cfg_indicatorDesaturate
    property var cfg_indicatorDesaturateDefault
    property var cfg_indicatorGrow
    property var cfg_indicatorGrowDefault
    property var cfg_indicatorGrowFactor
    property var cfg_indicatorGrowFactorDefault
    property var cfg_indicatorEdgeOffset
    property var cfg_indicatorEdgeOffsetDefault
    property var cfg_indicatorSize
    property var cfg_indicatorSizeDefault
    property var cfg_indicatorLength
    property var cfg_indicatorLengthDefault
    property var cfg_indicatorRadius
    property var cfg_indicatorRadiusDefault
    property var cfg_indicatorShrink
    property var cfg_indicatorShrinkDefault
    property var cfg_indicatorDominantColor
    property var cfg_indicatorDominantColorDefault
    property var cfg_indicatorAccentColor
    property var cfg_indicatorAccentColorDefault
    property var cfg_indicatorCustomColor
    property var cfg_indicatorCustomColorDefault
    property var cfg_useBorders
    property var cfg_useBordersDefault
    property var cfg_taskSpacingSize
    property var cfg_taskSpacingSizeDefault
    property var cfg_buttonColorize
    property var cfg_buttonColorizeDefault
    property var cfg_buttonColorizeInactive
    property var cfg_buttonColorizeInactiveDefault
    property var cfg_buttonColorizeDominant
    property var cfg_buttonColorizeDominantDefault
    property var cfg_buttonColorizeCustom
    property var cfg_buttonColorizeCustomDefault
    property var cfg_disableButtonSvg
    property var cfg_disableButtonSvgDefault
    property var cfg_disableButtonInactiveSvg
    property var cfg_disableButtonInactiveSvgDefault
    property var cfg_overridePlasmaButtonDirection
    property var cfg_overridePlasmaButtonDirectionDefault
    property var cfg_plasmaButtonDirection
    property var cfg_plasmaButtonDirectionDefault
    property var cfg_indicatorReverse
    property var cfg_indicatorReverseDefault
    property var cfg_indicatorOverride
    property var cfg_indicatorOverrideDefault
}